-- ============================================
-- PRIME VIDEO CLONE — SEED DATA
-- Run this AFTER supabase-schema.sql
-- ============================================

-- ==== MOVIES ====
INSERT INTO content (title, description, type, genre, year, rating, imdb_score, duration, image_url, banner_url, badge, is_prime, is_featured, sort_order) VALUES
('Dune: Part Two', 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.', 'movie', 'Sci-Fi, Adventure', 2024, 'PG-13', 8.9, '2h 46m', 'https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5YzAwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg', 'https://images.unsplash.com/photo-1534809027769-b00d750a6bac?w=1920&q=80', 'Featured Movie', true, true, 1),
('The Tomorrow War', 'A man is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.', 'movie', 'Action, Sci-Fi', 2021, 'PG-13', 6.7, '2h 18m', 'https://m.media-amazon.com/images/M/MV5BMDI3Y2RhNGEtYzE0OS00ZjAyLTkyOGYtMGI2OTM5NjljYzI3XkEyXkFqcGc@._V1_.jpg', NULL, 'Prime Original', true, false, 2),
('Sound of Metal', 'A drummer begins to lose his hearing and must choose between his music career and a new way of life.', 'movie', 'Drama, Music', 2019, 'R', 7.8, '2h 10m', 'https://m.media-amazon.com/images/M/MV5BOWI5MWFjODAtY2E0My00ZDYzLTk0ZWEtYzE2MGRkMDUyNmNlXkEyXkFqcGc@._V1_.jpg', NULL, 'Prime Original', true, false, 3),
('Air', 'The story of how Nike created the Air Jordan brand and changed sports marketing forever.', 'movie', 'Drama, Biography', 2023, 'R', 7.4, '1h 52m', 'https://m.media-amazon.com/images/M/MV5BYTUxYjczMWUtYzlkZC00NTcwLWE3NTgtMDdjMWM0OTM5ZmRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', NULL, 'Prime Original', true, false, 4),
('Without Remorse', 'An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his wife.', 'movie', 'Action, Thriller', 2021, 'R', 5.8, '1h 49m', 'https://m.media-amazon.com/images/M/MV5BOTRiMjQ3NWUtOWE3MS00YjIxLTk0ZjctMDRjMGQ0ZjA1NDgzXkEyXkFqcGc@._V1_.jpg', NULL, NULL, true, false, 5),
('Manchester by the Sea', 'A depressed uncle is asked to take care of his teenage nephew.', 'movie', 'Drama', 2016, 'R', 7.8, '2h 17m', 'https://m.media-amazon.com/images/M/MV5BNjI5NDkwNjg0N15BMl5BanBnXkFtZTgwOTk1NTQxMDE@._V1_.jpg', NULL, NULL, true, false, 6),
('John Wick: Chapter 4', 'John Wick uncovers a path to defeating the High Table, but must face a new enemy.', 'movie', 'Action, Crime', 2023, 'R', 7.7, '2h 49m', 'https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_.jpg', NULL, NULL, false, false, 7),
('The Batman', 'Batman ventures into Gotham City underworld when a sadistic killer leaves behind clues.', 'movie', 'Action, Crime', 2022, 'PG-13', 7.8, '2h 56m', 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg', NULL, NULL, false, false, 8),
('Top Gun: Maverick', 'After thirty years, Maverick is still pushing the envelope as a top naval aviator.', 'movie', 'Action, Drama', 2022, 'PG-13', 8.3, '2h 10m', 'https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg', NULL, NULL, false, false, 9),
('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption.', 'movie', 'Drama', 1994, 'R', 9.3, '2h 22m', 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg', NULL, NULL, false, false, 10),
('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.', 'movie', 'Crime, Drama', 1972, 'R', 9.2, '2h 55m', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg', NULL, NULL, false, false, 11),
('The Dark Knight', 'Batman must accept one of the greatest psychological and physical tests to fight injustice.', 'movie', 'Action, Crime', 2008, 'PG-13', 9.0, '2h 32m', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg', NULL, NULL, false, false, 12),
('Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.', 'movie', 'Sci-Fi, Action', 2010, 'PG-13', 8.8, '2h 28m', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg', NULL, NULL, false, false, 13),
('Interstellar', 'Explorers travel through a wormhole in space in an attempt to ensure humanitys survival.', 'movie', 'Sci-Fi, Adventure', 2014, 'PG-13', 8.7, '2h 49m', 'https://m.media-amazon.com/images/M/MV5BOTI4MjdmYzQtNjIyZi00YjE5LTlhMmMtOGFkMTAzMDNjYzEyXkEyXkFqcGc@._V1_.jpg', NULL, NULL, false, false, 14),
('Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor.', 'movie', 'Action, Drama', 2000, 'R', 8.5, '2h 35m', 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_.jpg', NULL, NULL, false, false, 15),
('Mad Max: Fury Road', 'In a post-apocalyptic wasteland, Max teams up with Furiosa to flee a tyrant.', 'movie', 'Action, Adventure', 2015, 'R', 8.1, '2h', 'https://m.media-amazon.com/images/M/MV5BMjMwMzE1OTc0OF5BMl5BanBnXkFtZTgwMDk1MTc5NTE@._V1_.jpg', NULL, NULL, false, false, 16),
('The Matrix', 'A hacker discovers that reality as he knows it is a simulation and joins a rebellion.', 'movie', 'Sci-Fi, Action', 1999, 'R', 8.7, '2h 16m', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg', NULL, NULL, false, false, 17),
('Mission: Impossible - Fallout', 'Ethan Hunt and his team race against time after a mission gone wrong.', 'movie', 'Action, Adventure', 2018, 'PG-13', 7.7, '2h 27m', 'https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg', NULL, NULL, false, false, 18);

-- ==== TV SHOWS ====
INSERT INTO content (title, description, type, genre, year, rating, imdb_score, seasons, image_url, banner_url, badge, is_prime, is_featured, sort_order) VALUES
('The Boys', 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.', 'tvshow', 'Action, Comedy, Crime', 2019, 'TV-MA', 8.7, 4, 'https://m.media-amazon.com/images/M/MV5BOTVhNzZlNDAtNDc2My00MTA2LWI1YzMtZTk0ZDRkMjJhNTE2XkEyXkFqcGc@._V1_.jpg', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1920&q=80', 'Prime Original Series', true, true, 1),
('Jack Ryan', 'CIA analyst Jack Ryan stumbles upon a suspicious series of bank transfers and is thrust into a dangerous mission.', 'tvshow', 'Action, Drama, Thriller', 2018, 'TV-MA', 8.1, 4, 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg', NULL, NULL, true, false, 2),
('The Wheel of Time', 'Set in a sprawling epic world, a woman and five companions embark on a journey across the world.', 'tvshow', 'Action, Adventure, Fantasy', 2021, 'TV-14', 7.1, 2, 'https://m.media-amazon.com/images/M/MV5BMDI5ZWJhOWItYTlhOC00YWRhLTk5NDYtNGIyODI5MjM5YjA4XkEyXkFqcGc@._V1_.jpg', NULL, NULL, true, false, 3),
('Mrs. Maisel', 'A housewife in the 1950s discovers she has a talent for stand-up comedy.', 'tvshow', 'Comedy, Drama', 2017, 'TV-MA', 8.7, 5, 'https://m.media-amazon.com/images/M/MV5BZjBiOGIyY2YtOTA3OC00YzY1LThkYjktMGRkYTNhNTQ1ZjJmXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', NULL, NULL, true, false, 4),
('Invincible', 'An adult animated series about a teenager whose father is the most powerful superhero on the planet.', 'tvshow', 'Animation, Action, Drama', 2021, 'TV-MA', 8.7, 2, 'https://m.media-amazon.com/images/M/MV5MDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', NULL, NULL, true, false, 5),
('Reacher', 'Jack Reacher, a veteran military police investigator, has entered civilian life. When he is falsely accused of murder.', 'tvshow', 'Action, Crime, Drama', 2022, 'TV-MA', 8.1, 2, 'https://m.media-amazon.com/images/M/MV5BNGEyOGJiNWEtMTgwMi00ODNmLTliM2ItMjc2NDgxMDY0NDY2XkEyXkFqcGc@._V1_.jpg', NULL, NULL, true, false, 6),
('Fallout', 'In a future post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers.', 'tvshow', 'Action, Adventure, Drama', 2024, 'TV-MA', 8.5, 1, 'https://m.media-amazon.com/images/M/MV5BNDUzOGI0MzYtZGY2OS00MmI4LWFhMjMtNGU3NWY3OTBhYjUzXkEyXkFqcGc@._V1_.jpg', NULL, 'New', true, false, 7),
('Citadel', 'Global spy action series. Eight years ago, the spy agency Citadel fell and agents had their memories wiped.', 'tvshow', 'Action, Drama, Sci-Fi', 2023, 'TV-MA', 5.7, 1, 'https://m.media-amazon.com/images/M/MV5BN2Y3OWQ5NDMtNDY1NC00N2YzLWE2NjYtZWRkOWRjOWI0NjM2XkEyXkFqcGc@._V1_.jpg', NULL, NULL, true, false, 8),
('Homecoming', 'A caseworker at an experimental facility begins to realize there is nothing ordinary about her job.', 'tvshow', 'Drama, Mystery, Thriller', 2018, 'TV-MA', 7.5, 2, 'https://m.media-amazon.com/images/M/MV5BMTk3MjkzODczOF5BMl5BanBnXkFtZTgwNjczMTMxNDM@._V1_.jpg', NULL, NULL, true, false, 9),
('The Grand Tour', 'Jeremy Clarkson, Richard Hammond and James May embark on an adventure across the globe.', 'tvshow', 'Adventure, Comedy', 2016, 'TV-PG', 8.7, 5, 'https://m.media-amazon.com/images/M/MV5BODIwNDUxNjY2MF5BMl5BanBnXkFtZTgwNjM5MTEwMDE@._V1_.jpg', NULL, NULL, true, false, 10);

-- ==== LIVE CHANNELS ====
INSERT INTO content (title, description, type, genre, year, image_url, banner_url, is_live, is_featured, sort_order) VALUES
('Premier League', 'Live football matches from the English Premier League.', 'channel', 'Sports', 2024, 'https://images.unsplash.com/photo-1508098682722-e99c643e7f0b?w=400&q=80', 'https://images.unsplash.com/photo-1461896836934-bd45ba8b0e28?w=1920&q=80', true, true, 1),
('IPL 2024', 'Live cricket matches from the Indian Premier League.', 'channel', 'Sports', 2024, 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=400&q=80', NULL, true, false, 2),
('NBA Tonight', 'Live basketball games from the NBA.', 'channel', 'Sports', 2024, 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&q=80', NULL, true, false, 3),
('Grand Slam Tennis', 'Live tennis matches from Grand Slam tournaments.', 'channel', 'Sports', 2024, 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80', NULL, true, false, 4),
('Formula 1', 'Live Formula 1 races and qualifying sessions.', 'channel', 'Sports', 2024, 'https://images.unsplash.com/photo-1541252260730-0412e8e2108e?w=400&q=80', NULL, true, false, 5),
('World News Live', 'Breaking news from around the globe, 24/7.', 'channel', 'News', 2024, 'https://images.unsplash.com/photo-1504711434969-e33886168d6c?w=400&q=80', NULL, true, false, 6),
('Business Today', 'Financial markets, business analysis and stock updates.', 'channel', 'News', 2024, 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=400&q=80', NULL, true, false, 7),
('Headlines Now', 'Top headlines and breaking news stories.', 'channel', 'News', 2024, 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=400&q=80', NULL, true, false, 8),
('Tech Today', 'Latest technology news, reviews and announcements.', 'channel', 'News', 2024, 'https://images.unsplash.com/photo-1553484771-371a605b060b?w=400&q=80', NULL, true, false, 9),
('Music TV', '24/7 music videos and live performances.', 'channel', 'Entertainment', 2024, 'https://images.unsplash.com/photo-1616530940355-351fabd9524b?w=400&q=80', NULL, true, false, 10),
('Movie Channel', 'Around-the-clock movies from every genre.', 'channel', 'Entertainment', 2024, 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=400&q=80', NULL, true, false, 11),
('Comedy Central', 'Stand-up comedy, sitcoms and funny shows.', 'channel', 'Entertainment', 2024, 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=400&q=80', NULL, true, false, 12),
('Kids Zone', 'Family-friendly animation and kids shows.', 'channel', 'Kids', 2024, 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=400&q=80', NULL, true, false, 13);
